variable "name" { }
variable "name_suffix" { }
variable "region" { }
variable "subnets" { }
variable "ecs_service_security_groups" { }
variable "container_port" { }
variable "container_cpu" { }
variable "container_memory" { }
variable "ecr_repository_urls" { }
variable "service_desired_count" { }
